---
title: "オッズ比を使う理由と実験デザインについて"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 内容

オッズ比の用途とそれに関連する

コホート研究（前向き研究）

ケースコントロール研究（後ろ向き研究）

についてのまとめ。

# オッズ比

## ハジパタでの場合

特徴量ベクトル$\overrightarrow{x}$の中のxが１増えた時を考える.

増えた後の特徴量ベクトルは$\overrightarrow{x'}=(1,(x+1))^T$

２値問題として、事象が”１”になる確率が$P(1|\overrightarrow{x})$と$P(1|\overrightarrow{x'})$でどう変わるかオッズ比を計算してみる。
オッズ比を求めると、ロジットの式を用いて

$$

odd_rate = \frac{\frac{P(1|\overrightarrow{x'})}{(1-P(1|\overrightarrow{x'}))}}{\frac{P(1|\overrightarrow{x})}{(1-P(1|\overrightarrow{x}))}}=\frac{exp(w_0+w_1(x+1))}{exp(w_0+w_1(x))}=exp(w_1)

$$

※計算式を簡単にするため、特徴量は０次項を含めて２次元とした。
結果として、xが１増えると、事象が１になる確率のオッズ比は$exp(w_1)$増加する。

### これの何がいいか？　→　機械学習の評価に良い
２値分類での予測問題を考える。

事象が１になる確率というのは、予測精度が１００％ということである。

そして、機械学習の評価としては、

20%の予測が25%になることと

90%の予測が95%になることの

価値は設計者としては大きく異なるはずであり、その意図をうまく性能指標として組み込みたい

つまり、100%に近く改善の方がより大きな指標値になること。
オッズ比はまさにそれになっており、100%(=1)に近くこと、指数関数的に数値が上がるのである。

例）
0.9から0.99の改善の場合 -> オッズ比　11     リスク比 1.1

0.5から0.55の改善の場合 -> オッズ比　1.22　リスク比 1.1
リスク比はどちらも変わらないが、オッズ比は大きく異なる


# コホート（前向き）研究
介入・非介入（DMの送付先指定や投薬指定など）が制御できる。
しかし、イベントの発現（商品の購入・非購入や発病・非発病など）
は制御できない。

コホート研究の場合、
反応度が低い事象のことを想定して、十分な大きさの観測数の設定や
脱落者対応が必要。

# ケースコントロール（後ろ向き）研究
イベントの発現（商品の購入・非購入や発病・非発病など）は制御できるが
介入・非介入（DMの送付先指定や投薬指定など）ができない
（＝すでに実行された結果を元に研究・分析する）

また大きな特徴として、介入・非介入がRCTの下で行われていない場合が多く、
セレクションバイアスが混入している。



過去の時点の分析目的があり、それに基づいたデータであれば因果推定ができる。

でもそれはそもそも前向き研究なのである。

この場合の後ろ向き研究の定義は

イベントの発現・非発現を所定のサンプル数集めることが目的。
そのサンプルの背景に関しては、考慮しないということ（考慮することもできるが最優先ではない）
背景を考慮すると十分なサンプル数が集まらない可能性がある。

そのため、因果推定のためのリスク比やリスク差は計算できない。











